# /etc/mosquitto/conf.d/pi_hub.conf

# TCP Listener for ESP32-S3, ESP32-CAM & Local Python Daemons
listener 1883 0.0.0.0
allow_anonymous true

# WebSocket Listener for React Web-UI Clients (Browser / Mobile)
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true